name: Django BLOG CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Selamdur
      run: echo "oğuzhan"
    - name: Run Tests
      run: |
        python manage.py test
